<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>ServicesHomePage</name>
   <tag></tag>
   <elementGuidId>8bfbe44e-861e-43ba-be8b-cea31239dadd</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>${shop_auth_token}</value>
      <webElementGuid>6d11cea8-04a2-4da5-8c08-06b531b72d0e</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>8.5.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>${URL}/s/TP-FOOD/dw/shop/v23_1/content/foodhome?lat=19.304440&amp;long=-99.189490&amp;time=21:53&amp;currentPage=0&amp;limit=4&amp;pageSize=2&amp;currentPage=1&amp;sort=desc</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.URL</defaultValue>
      <description></description>
      <id>ce080d26-1a3d-45f7-a8be-1621f2ad3155</id>
      <masked>false</masked>
      <name>URL</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.shop_auth_token</defaultValue>
      <description></description>
      <id>6c9c551c-8948-400e-afaf-7e0b9bf1a873</id>
      <masked>false</masked>
      <name>shop_auth_token</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
